name: Run Tests
  
on: [workflow_dispatch, push]  
  
jobs:  
  build:  
    runs-on: self-hosted  
    strategy:  
      matrix:  
        python-version: ["3.11.2"]  
  
    steps:  
      - uses: actions/checkout@v3  
      # - name: Set up Python ${{ matrix.python-version }}  
      #   uses: actions/setup-python@v4  
      #   with:  
      #     python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi; pip install coverage; pip install pytest;
      - name: Lint with Ruff  
        run: |  
          pip install ruff  
          ruff --format=github --target-version=py310 .  
        continue-on-error: true  
      - name: Test with pytest  
        run: |  
          python -m coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          python -m coverage report -m
