name: Run Tests
  
on: [workflow_dispatch, push]  
  
jobs:  
  build:  
    runs-on: self-hosted  
    strategy:  
      matrix:  
        python-version: ["3.11.2"]  
  
    steps:  
      - uses: actions/checkout@v3  
      # - name: Set up Python ${{ matrix.python-version }}  
      #   uses: actions/setup-python@v4  
      #   with:  
      #     python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi; pip install coverage; pip install pytest; export PYTHONIOENCODING=utf8;
      - name: Flash STM32_FW 
        run: |  
          cd src/STM32_FW;make;cp build/STM32_FW.elf ../xpacks/.bin/STM32_fw.elf;
          sudo ../xpacks/.bin/openocd -s "/usr/local/share/openocd/scripts" -f "interface/stlink-v2.cfg" -f "target/stm32f4x.cfg" -c "program STM32_FW.elf verify reset exit"
        continue-on-error: true 
      - name: Test with pytest  
        run: |  
          python -m coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          python -m coverage report -m
